import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import Navbar from "@/components/Navbar";
import { Heart } from "lucide-react";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NPM Check Updates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
           <footer className="absolute bottom-0 w-full flex justify-center mb-4">
              <p className="flex items-center flex-wrap justify-center">&copy; 2024, Npm Check is made with
                <Heart className="text-[#C12127] h-5 w-5 mx-1" fill="#C12127"/>  by
                <Link className="text-[#C12127] ml-1" href="https://www.linkedin.com/in/ian-duhamel/">{" "} Ian Duhamel</Link>
              </p>
            </footer>
        </ThemeProvider>
        <Toaster/>
      </body>
    </html>
  );
}
